name: Fixed Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # تحديث للإصدار 4
      
      - name: Unzip safely
        run: unzip *.zip
        
      - name: set up JDK 17
        uses: actions/setup-java@v4 # تحديث للإصدار 4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
          
      - name: Find and Build
        run: |
          # البحث عن ملف gradlew وتفعيله
          GRADLEW_PATH=$(find . -name gradlew)
          chmod +x $GRADLEW_PATH
          cd $(dirname $GRADLEW_PATH)
          ./gradlew assembleDebug
          
      - name: Upload APK
        uses: actions/upload-artifact@v4 # التحديث المطلوب لحل المشكلة (v4)
        with:
          name: Keyboard-Romantic-Final
          path: "**/build/outputs/apk/debug/*.apk"
          
